<?xml version="1.0" encoding="utf-8"?><Database Name="Login_Database" Class="LoginClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Login" Member="Logins">
    <Type Name="Login">
      <Column Name="[User ID]" Member="User_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[User Name]" Member="User_Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>