<?xml version="1.0" encoding="utf-8"?><Database Name="UserList" Class="UserListClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.UserList" Member="UserLists">
    <Type Name="UserList">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tasks" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Done" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SerialNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>